In [198]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [199]:
import plotly.express as px
import warnings
pd.set_option('display.max_columns',None)
pd.options.display.float_format='{:.0f}'.format
warnings.filterwarnings('ignore')

In [200]:
data = pd.read_csv('ShopeeData_cleaned.csv')
data.head()

,itemid,liked_count,cmt_count,discount,shop_rating,historical_sold,price,rating_star,rating_count,rcount_with_context,Date
0,20030969576,25677,9675,11,5,35701,9200000000,5,9675,5639,2024-03-10
1,19527695224,20032,6504,40,5,23141,6600000000,5,6504,4034,2024-03-10
2,21407947288,18760,2611,4,5,8489,11500000000,5,2611,1441,2024-03-10
3,14185378989,14582,8600,47,5,28022,7900000000,5,8602,5430,2024-03-10
4,10001549800,29919,19065,22,5,69948,10900000000,5,19068,10715,2024-03-10

In [204]:
data_sorted = data.sort_values(by=['itemid', 'Date'])
# Sử dụng phương thức groupby để nhóm dữ liệu theo 'itemid'
grouped = data_sorted.groupby('itemid')

data_sorted['num_sold'] = grouped['historical_sold'].diff()
data_sorted

,itemid,liked_count,cmt_count,discount,shop_rating,historical_sold,price,rating_star,rating_count,rcount_with_context,Date,num_sold
84,1985669632,24102,404,23,5,1204,33900000000,5,403,207,2024-03-10,NaN
256,1985669632,24104,404,23,5,1206,33900000000,5,403,207,2024-03-11,2
429,1985669632,24105,405,23,5,1210,33900000000,5,404,208,2024-03-12,4
600,1985669632,24105,406,23,5,1214,33900000000,5,405,208,2024-03-13,4
767,1985669632,24105,406,23,5,1216,33900000000,5,405,208,2024-03-14,2
...,...,...,...,...,...,...,...,...,...,...,...,...
3111,25919955014,1,0,41,5,0,38500000000,0,0,0,2024-03-27,0
3295,25919955014,1,0,41,5,0,38500000000,0,0,0,2024-03-28,0
3481,25919955014,1,0,41,5,0,38500000000,0,0,0,2024-03-29,0
3666,25919955014,1,0,41,5,0,38500000000,0,0,0,2024-03-30,0
3853,25919955014,1,0,41,5,0,38500000000,0,0,0,2024-03-31,0

In [176]:
data_sorted = data.sort_values(by=['itemid', 'Date'])

# Sử dụng phương thức groupby để nhóm dữ liệu theo 'itemid'
grouped = data_sorted.groupby('itemid')

# Tính toán sự khác biệt giữa các giá trị 'historical_sold' của các ngày liên tiếp
# data_sorted['num_sold'] = grouped['historical_sold'].diff()

# # Khởi tạo giá trị 'num_sold' của ngày đầu tiên trong mỗi nhóm là giá trị 'historical_sold' ban đầu
# data_sorted['num_sold'] = data_sorted['num_sold'].fillna(method='bfill')

In [177]:
data_sorted = data_sorted.drop(columns=['historical_sold'])
data_sorted.head()

,itemid,liked_count,cmt_count,discount,shop_rating,price,rating_star,rating_count,rcount_with_context,Date,num_sold
84,1985669632,24102,404,23,5,33900000000,5,403,207,2024-03-10,2
256,1985669632,24104,404,23,5,33900000000,5,403,207,2024-03-11,2
429,1985669632,24105,405,23,5,33900000000,5,404,208,2024-03-12,4
600,1985669632,24105,406,23,5,33900000000,5,405,208,2024-03-13,4
767,1985669632,24105,406,23,5,33900000000,5,405,208,2024-03-14,2

In [178]:
data_sorted.sort_index(inplace=True)
data_sorted

,itemid,liked_count,cmt_count,discount,shop_rating,price,rating_star,rating_count,rcount_with_context,Date,num_sold
0,20030969576,25677,9675,11,5,9200000000,5,9675,5639,2024-03-10,60
1,19527695224,20032,6504,40,5,6600000000,5,6504,4034,2024-03-10,79
2,21407947288,18760,2611,4,5,11500000000,5,2611,1441,2024-03-10,10
3,14185378989,14582,8600,47,5,7900000000,5,8602,5430,2024-03-10,102
4,10001549800,29919,19065,22,5,10900000000,5,19068,10715,2024-03-10,159
...,...,...,...,...,...,...,...,...,...,...,...
3862,7760455431,7,2,17,5,99900000000,5,2,1,2024-03-31,0
3863,23130014016,3,2,14,5,33900000000,5,2,1,2024-03-31,0
3864,22884871515,1,0,10,5,23850000000,0,0,0,2024-03-31,0
3865,22262533851,1,0,15,5,65000000000,0,0,0,2024-03-31,0
3866,15689885742,11536,0,30,5,77000000000,0,0,0,2024-03-31,0

In [179]:
data_day_30 = data_sorted[data_sorted['Date'] == '2024-03-30']
data_day_31 = data_sorted[data_sorted['Date'] == '2024-03-31']
data_day_30.set_index('Date', inplace=True)
data_day_31.set_index('Date', inplace=True)

In [180]:
data_train = data_sorted[data_sorted['Date'] < '2024-03-30']
data_test = data_sorted[data_sorted['Date'] >= '2024-03-30']

In [181]:
data_train.set_index('Date', inplace=True)
data_test.set_index('Date', inplace=True)

In [182]:
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error

In [183]:
x_train = data_train.drop(columns=['num_sold'])
y_train = data_train['num_sold']
x_test = data_test.drop(columns=['num_sold'])
y_test = data_test['num_sold']

In [184]:
model = XGBRegressor(n_estimators=1000, learning_rate=0.012005)
model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.012005, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=1000, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

### Train từ ngày 10 đến ngày 29, dự đoán tập dữ liệu gồm ngày 30 và 31

In [185]:
y_pred = model.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
mse

96.59685390173654

In [186]:
compare_train29_pred_30_31 = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred, 'itemid': data_test['itemid'], 'difference': round(y_test - y_pred).astype(int)})

compare_train29_pred_30_31.to_csv('compare_train29_pred_30_31.csv', index=False)
compare_train29_pred_30_31.head()

            Actual  Predicted       itemid  difference
Date
2024-03-30     188        187   2421653980           1
2024-03-30     112        185   5451541710         -73
2024-03-30     509        486  23232932577          23
2024-03-30     149        211  19127946184         -62
2024-03-30     132        182  10001549800         -50

### sử dụng tập train đến ngày 29 dự đoán ngày 30 và ngày 31

In [187]:
x_test_30 = data_day_30.drop(columns=['num_sold'])
y_test_30 = data_day_30['num_sold']
x_test_31 = data_day_31.drop(columns=['num_sold'])
y_test_31 = data_day_31['num_sold']

In [188]:
y_pred_30 = model.predict(x_test_30)
y_pred_31 = model.predict(x_test_31)

mse_30 = mean_squared_error(y_test_30, y_pred_30)
mse_31 = mean_squared_error(y_test_31, y_pred_31)
display(mse_30, mse_31)

136.74580846937187

56.013856582018676

### MSE ngày 30 là 136 và MSE ngày 31 là 56

In [189]:
compare_train29_pred30 = pd.DataFrame({'itemid': data_day_30['itemid'], 'Actual': y_test_30, 'Predicted': y_pred_30, 'difference': round(y_test_30 - y_pred_30).astype(int)})
compare_train29_pred31 = pd.DataFrame({'itemid': data_day_31['itemid'], 'Actual': y_test_31, 'Predicted': y_pred_31, 'difference': round(y_test_31 - y_pred_31).astype(int)})

compare_train29_pred30.to_csv('compare_train29_pred30.csv', index=False)
compare_train29_pred31.to_csv('compare_train29_pred31.csv', index=False)

### Train từ ngày 10 đến ngày 30, dự đoán ngày 31

In [193]:
data_train = data_sorted[data_sorted['Date'] < '2024-03-31']
data_test = data_sorted[data_sorted['Date'] >= '2024-03-31']

data_train.set_index('Date', inplace=True)
data_test.set_index('Date', inplace=True)

x_train = data_train.drop(columns=['num_sold'])
y_train = data_train['num_sold']
x_test = data_test.drop(columns=['num_sold'])
y_test = data_test['num_sold']

model = XGBRegressor(n_estimators=1000, learning_rate=0.012005)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
mse

33.12765469904042

In [194]:
compare_4 = pd.DataFrame({'itemid': data_test['itemid'], 'Actual': y_test, 'Predicted': y_pred, 'difference': round(y_test - y_pred).astype(int)})
compare_4.to_csv('compare_train30_pre31.csv')
compare_4.head(10)

                 itemid  Actual  Predicted  difference
Date
2024-03-31   2421653980     198        194           4
2024-03-31   5451541710     126        148         -22
2024-03-31  19127946184     183        189          -6
2024-03-31  10001549800     153        134          19
2024-03-31  16870222597     160        139          21
2024-03-31  20030969576      80         42          38
2024-03-31  22633042956      28         34          -6
2024-03-31  14185378989      68         54          14
2024-03-31  22637943287      57         80         -23
2024-03-31  19527695224      83         79           4

sau khi thêm dữ liệu của ngày 30 vào thì việc dự đoán chính xác hơn, MSE giảm từ 56 về 33